-- MySQL Script generated by MySQL Workbench
-- Thu Feb 27 17:20:24 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dimension
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dimension` ;

-- -----------------------------------------------------
-- Schema dimension
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dimension` DEFAULT CHARACTER SET utf8 ;
USE `dimension` ;

-- -----------------------------------------------------
-- Table `dimension`.`Dimension`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dimension`.`Dimension` (
  `idDimension` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(60) NULL,
  `nivelCaos` INT NULL,
  `leyesFisicas` TEXT NULL,
  `habitantes` TEXT NULL,
  `diferencias` TEXT NULL,
  `amenazaPrincipal` TEXT NULL,
  `descripcion` TEXT NULL,
  `imagen` VARCHAR(100) NULL,
  PRIMARY KEY (`idDimension`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dimension`.`Portal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dimension`.`Portal` (
  `idPortal` INT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(60) NULL,
  `ubicacionOrigen` VARCHAR(100) NULL,
  `metodoApertura` VARCHAR(50) NULL,
  `estabilidad` VARCHAR(100) NULL,
  `descripcion` TEXT NULL,
  `imagen` VARCHAR(100) NULL,
  `idDimension` INT NOT NULL,
  PRIMARY KEY (`idPortal`, `idDimension`),
  CONSTRAINT `fk_Portal_Dimension`
    FOREIGN KEY (`idDimension`)
    REFERENCES `dimension`.`Dimension` (`idDimension`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Portal_Dimension_idx` ON `dimension`.`Portal` (`idDimension` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
